= OneCX Shell

== Licence
This software is licensed under the Apache License, Version 2.0.
You may obtain a copy of the license in the corresponding LICENSE file or visit the link:https://www.apache.org/licenses/LICENSE-2.0[Apache website] for more information.

== Contributing
We welcome contributions from the community.
If you would like to contribute to the development of OneCX Shell Software, please follow our contribution guidelines (tbd).

== What is Shell
Shell is the backbone of OneCX and serves essential data and acts as wrapper for all other applications.

== Key Features

* Serves essential data and acts as wrapper for all other applications.

== Issue tracking
All OneCX Shell issues are tracked and maintained at the link:https://xyz.com[issue tracking tool].

== Overview
tbd

== Getting Started
To get started with OneCX Shell Software, please refer to the following installation and setup instructions specific to each component:

* link:https://onecx.github.io/docs/onecx-shell/current/ui/index.html[OneCX Shell UI (User Interface) - Getting Started]
* link:https://onecx.github.io/docs/onecx-shell/current/bff/index.html[OneCX Shell Management BFF (Backend for Frontend) - Getting Started]

For detailed usage instructions and API documentation, please refer to the respective documentation files for each component.

== Roadmap
tbd